# Generated by Django 3.2.3 on 2021-05-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('owner_info', models.CharField(max_length=100)),
                ('employee_size', models.CharField(max_length=20)),
            ],
        ),
    ]
